services:
  postgres:
    image: postgres
    volumes:
      - ./scripts/createDB.sql:/docker-entrypoint-initdb.d/createDB.sql
    environment:
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "productsDB"
      POSTGRES_USER: "postgres"
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
      image: nodejschallenge
      build: . 
      volumes:
        - /downloadFiles
      ports:
        - 3000:3000
      depends_on:
        postgres:
          condition: service_healthy